# Generated by Django 5.0.3 on 2024-03-25 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerLink', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_cover',
            field=models.FileField(blank=True, default='media/default_profile_cover.jpg', null=True, upload_to='media/'),
        ),
    ]
