# Generated by Django 5.0.3 on 2024-03-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerLink', '0002_alter_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('PEDAGOGICAL', 'Activités pédagogiques'), ('RESEARCH', 'Activités de recherche'), ('REGULAR', 'Regular Post')], default='REGULAR', max_length=50),
        ),
    ]
