# Generated by Django 5.0.3 on 2024-03-29 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CareerLink', '0002_contactinfo_education_experience_interest_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interest',
            old_name='name',
            new_name='interests',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='name',
            new_name='skills',
        ),
    ]
