# Generated by Django 5.0.3 on 2024-03-20 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CareerLink', '0002_post_likes_alter_like_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_id',
            new_name='id',
        ),
    ]
