# Generated by Django 5.0.3 on 2024-03-26 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerLink', '0002_class_class_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='announcement_attachments/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='announcement_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CareerLink.class')),
            ],
        ),
    ]
