# Generated by Django 5.0.3 on 2024-03-27 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CareerLink', '0003_announcement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='associated_class',
            new_name='class_instance',
        ),
    ]
