# Generated by Django 5.0.3 on 2024-03-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerLink', '0003_alter_follow_followed_account_alter_follow_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='posts',
        ),
        migrations.AddField(
            model_name='user',
            name='posts',
            field=models.ManyToManyField(related_name='authors', to='CareerLink.post'),
        ),
    ]
