# Generated by Django 5.0.3 on 2024-03-23 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CareerLink', '0003_post_post_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='attachement',
            new_name='attachment',
        ),
    ]
