# Generated by Django 5.0.3 on 2024-03-29 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerLink', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(default='normal', max_length=50),
        ),
    ]
