# Generated by Django 5.0.3 on 2024-03-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerLink', '0004_rename_attachement_post_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_media',
            field=models.FileField(blank=True, null=True, upload_to='posts-files/'),
        ),
    ]
