# Generated by Django 5.0.3 on 2024-03-27 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerLink', '0006_assignment_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='submission',
            field=models.FileField(blank=True, null=True, upload_to='assignment_submissions/'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
