# Generated by Django 5.0.3 on 2024-03-27 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerLink', '0007_assignment_submission_assignment_submitted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_assignments', to='CareerLink.student'),
        ),
    ]
