# Generated by Django 5.0.3 on 2024-03-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerLink', '0009_offer_location_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='yearly_salary',
            field=models.FloatField(default=0.0),
        ),
    ]
