# Generated by Django 5.0.3 on 2024-03-29 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CareerLink', '0010_offer_yearly_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='yearly_salary',
            new_name='salary',
        ),
    ]
