# Generated by Django 5.0.3 on 2024-03-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerLink', '0013_user_birth_date_user_country_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='correct_answers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
