# Generated by Django 5.0.3 on 2024-04-01 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CareerLink', '0016_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestream',
            name='class_room',
        ),
        migrations.RemoveField(
            model_name='livestream',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='LiveStream',
        ),
    ]
