# Generated by Django 5.0.3 on 2024-04-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerLink', '0019_alter_education_end_date_alter_education_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(default='', max_length=100),
        ),
    ]
